package com.sample

import com.sample.Example.Message;

rule "Hello World"
    when
        m : Message( message == Message.HELLO, myMessage : message )
        minimalAge: Message ( age > 18 )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye!!" );
        update( m );
end

rule "GoodBye"
    when
         m : Message( message == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end